### PR TITLE
fix: support undefined app.config `nuxtIcon`

### LINKED ISSUE #100: After update: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'replace')
After update getting this error with icons failing to load. Found where error is coming from. Fixed when removing ":.replace(/^i-/, ''))"

From changelog:
- const iconName = computed(() => (appConfig.nuxtIcon?.aliases || {})[props.name] || props.name)
+ const iconName = computed(() => ((appConfig.nuxtIcon?.aliases || {})[props.name] || props.name).replace(/^i-/, ''))

Console error:
Icon.vue:25  Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'replace')
    at ReactiveEffect.fn (Icon.vue:25:97)
    at ReactiveEffect.run (chunk-BVQHDTV7.js:423:19)
    at get value [as value] (chunk-BVQHDTV7.js:1383:35)
    at Icon.vue:54:22
    at callWithErrorHandling (chunk-BVQHDTV7.js:1565:32)
    at ReactiveEffect.getter [as fn] (chunk-BVQHDTV7.js:3099:22)
    at ReactiveEffect.run (chunk-BVQHDTV7.js:423:19)
    at doWatch (chunk-BVQHDTV7.js:3195:26)
    at watch (chunk-BVQHDTV7.js:3050:10)
    at setup (Icon.vue:54:1)

### PR DESCRIPTION
**Pull request by pixelastronauts**
Resolves #100 

### Problem

While accessing properties of `nuxtIcon`, the application would throw a `TypeError` if `nuxtIcon` was undefined.

### Solution

Added optional chaining (`?.`) to safely access the nested properties of `nuxtIcon`.

### Changes

- Implemented optional chaining to check the existence of `nuxtIcon` before trying to access its `aliases` property.
- This resolves the error: "TypeError: Cannot read properties of undefined (reading 'aliases')".

### CODE REVIEW

**Comment by xin0907** [comment]
I've had this problem too and I think you're right

File: src/runtime/Icon.vue [hunk 1]
```diff
@@ -59,7 +59,7 @@ watch(() => appConfig.nuxtIcon?.iconifyApiOptions, () => {
 const state = useState<Record<string, IconifyIcon | undefined>>('icons', () => ({}))
 const isFetching = ref(false)
 const iconName = computed(() => {
-  if (appConfig.nuxtIcon.aliases && appConfig.nuxtIcon.aliases[props.name]) {
+  if (appConfig.nuxtIcon?.aliases && appConfig.nuxtIcon.aliases[props.name]) {
```
Comment (kyranet) [inline src/runtime/Icon.vue:62]: This can be further refactored with a single chain:
```suggestion
  if (appConfig.nuxtIcon?.aliases?.[props.name]) {
```

**Comment by harlan-zw** [comment]
Thanks, going to merge this as it's blocking me as well

**Comment by Atinux** [comment]
Sorry about this, just released as 0.6.1
